<script>
    const placeholderArticles = [
        {
            title: 'State of the League 2025',
            date: 'January 1, 2025',
            content: `A brief look at where every team stands heading into the new season. Future articles generated by the AI agent will replace this text.`,
        },
        {
            title: 'Draft Recap: Early Thoughts',
            date: 'August 15, 2025',
            content: `Highlights from the most recent rookie draft and initial reactions.`,
        },
    ];
</script>

<style>
    #main {
        margin: 30px auto;
        width: 95%;
        max-width: 1000px;
    }
</style>

<div id="main">
    <h1>Articles</h1>
    {#each placeholderArticles as article}
        <article style="margin-bottom: 2rem;">
            <h2>{article.title}</h2>
            <small>{article.date}</small>
            <p>{article.content}</p>
        </article>
    {/each}
</div>
