export const placeholderArticles = [
  {
    slug: 'state-of-the-league-2025',
    title: 'State of the League 2025',
    date: 'January 1, 2025',
    content: `A brief look at where every team stands heading into the new season. Future articles generated by the AI agent will replace this text.`,
  },
  {
    slug: 'draft-recap-2025',
    title: 'Draft Recap: Early Thoughts',
    date: 'August 15, 2025',
    content: `Highlights from the most recent rookie draft and initial reactions.`,
  },
];
